### ISSUE TITLE
P51のソフトマックス交差エントロピー損失の式

### ISSUE THREAD

**Issue by bruceZHXH** [miyamotok0105/pytorchapibook#10]
P51の真ん中ほど、ソフトマックス交差エントロピー損失の式は間違ったのではないかと思います。
分母は分子のlog関数の中に入れ、分母とするのではないでしょうか。

**Comment by hei4** [comment]
ご指摘ありがとうございます。ご指摘の通り、ソフトマックスでクラス確率にしたロジットを対数の中に入れる必要があります。

反映させていただきました。ありがとうございました。
