### ISSUE TITLE
LSTMを使用した文章分類：IMDB

### ISSUE THREAD

**Issue by yokohama11** [miyamotok0105/pytorchapibook#12]
以下コードを実行するとエラーが出ます。
修正されたコードはあるでしょうか？

# 前処理用の機能のFieldをセットアップ
# トークン化の方式を指定
tokenize = lambda x: x.split()
#Field
#include_lengths=Trueでイテレータが長さも含めたタプルを返す
#batch_first=Trueにしてる
TEXT = data.Field(sequential=True, tokenize=tokenize, lower=True, include_lengths=True, batch_first=True, fix_length=200)
・・・・

AttributeError                            Traceback (most recent call last)
<ipython-input-8-918aec1541b4> in <module>
      5 #include_lengths=Trueでイテレータが長さも含めたタプルを返す
      6 #batch_first=Trueにしてる
----> 7 TEXT = data.Field(sequential=True, tokenize=tokenize, lower=True, include_lengths=True, batch_first=True, fix_length=200)
      8 #LabelField
      9 LABEL = data.LabelField()

AttributeError: module 'torchtext.data' has no attribute 'Field'

**Comment by ayukat1016** [comment]
yokohama11様

執筆者の毛利と申します。
ご連絡が遅れ失礼いたしました。

5章のソースコードは書籍のp433のライブラリで動きます。
お手数ですが、以下のソースコードの実行して、バージョンを戻した上で
再度エラーが出るセルを実行して頂けないでしょうか？
（Colabの場合、バージョンを戻した後に、ランタイムを再起動したいと、バージョン戻しが反映しないので、ご注意ください。）

# #colabを使う方はこちらを使用ください。
!pip install torch==0.4.1
!pip install torchvision==0.2.1
!pip install numpy==1.14.6
!pip install matplotlib==2.1.2
!pip install pillow==5.0.0
!pip install opencv-python==3.4.3.18
!pip install torchtext==0.3.1

以下のソースコードの先頭のセルをコメントアウトして実行します。
https://github.com/miyamotok0105/pytorch_handbook/blob/master/chapter5/section5_4.ipynb

**Comment by hei4** [comment]
本件クローズいたします。
