### ISSUE TITLE
誤植の指摘

### ISSUE THREAD

**Issue by minoki** [miyamotok0105/pytorchapibook#6]
本書を読んで気づいた誤植等を指摘させていただきます。

|ページ|誤|正|
|:-:|:-:|:-:|
| 4章 p93 本文 | torchvidsion.models | torchvision.models |
| 6章 p165 本文 | 'tain+unlabeled' | 'train+unlabeled' |
| 6章 p167 本文 | real_targetl「1」 | 「1」（？） |
| 同 | ずなわち | すなわち |
| 6章 p172 コードのコメント内 | One-Hoe | One-Hot |
| 6章 p176 本文 | real_image_lagel | real_image_label |
| 7章 p192本文  |（同じクラスのバウンディングボックス）通し | 同士 |
| 8章 p262活用メモ | OneHot-Encording | OneHot-Encoding |
| 8章 p285 torch.roundの解説 | 実数を四捨五入で整数に丸めます。 | 実数を最も近い整数に丸めます。（「四捨五入」ではない） |
| 9章 p297 | Flattend Covolution | Flattened Convolution |

**Comment by hei4** [comment]
ご指摘ありがとうございます。正誤表に反映させていただきました。

rPentominoさんの [Issue](https://github.com/miyamotok0105/pytorch_handbook/issues/8) と合わせてcloseさせていただきます。

ありがとうございました。
