### ISSUE TITLE
Google Colabでsection2_2.ipynbを実行しようとするといきなりエラーになる

### ISSUE THREAD

**Issue by makaishi2** [miyamotok0105/pytorchapibook#7]
最初のnotebookの先頭でいきなりエラーになってしまいました。
対応方法をご教授いただきたく

![スクリーンショット 2021-01-06 19 25 33](https://user-images.githubusercontent.com/25073940/103758224-3ebdcb00-5055-11eb-924c-c28a542900cd.png)

**Comment by hei4** [comment]
おそらくですが、torchvisionをインストールされていないのではないでしょうか。

google colaboを使用される場合は、section2_2.ipynbの先頭セルのコメントアウトを解除して先頭セルを実行してください。

ローカル環境で実行される場合は、pipなどでtorchvision 0.2.1 をインストールしてください。

```
pip install torchvision==0.2.1
```

実行された環境が分からないため、いったんこちらのIssueはクローズさせていただきます。
