### ISSUE TITLE
minokiさんの修正の再修正

### ISSUE THREAD

**Issue by rPentomino** [miyamotok0105/pytorchapibook#8]
御著、便利に利用させていただいております。
ありがとうございます。
下記の件、気が付きましたのでお知らせいたします。

■ 8章 p285 torch.roundの解説

minokiさんが

	実数を最も近い整数に丸めます。（「四捨五入」ではない）

と修正を入れられていますが、元の

	実数を四捨五入で整数に丸めます。

で問題ないと思います。

ただし、この四捨五入アルゴリズム（Python全般の四捨五入）は、「JIS Z 8401」規格に準拠しています。

この仕様では、算数で教わるものとは違い、一つ上の桁のパリティによって「.5」の扱いが変わります。
この仕様を知らない方は多いので、脚注を入れていただければさらに良かったかなと思います。

**Comment by hei4** [comment]
フォローいただきありがとうございます。closeいたします。
